# Generated by Django 6.0.2 on 2026-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rektor', 'Rektor (Super Admin)'), ('prorektor', 'Prorektor'), ('tyuter', 'Tyuter'), ('oquv_bolimi', "O'quv Bo'limi"), ('inspekciya', 'Inspekciya'), ('kadirlar', "Kadirlar Bo'limi"), ('kutubxona', 'Kutubxona'), ('ombor', 'Ombor')], default='tyuter', max_length=20),
        ),
    ]
