# Generated by Django 6.0.2 on 2026-02-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonAnalysis',
        ),
    ]
