# Generated by Django 6.0.2 on 2026-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rektor', 'Rektor (Super Admin)'), ('prorektor', 'Prorektor'), ('tyuter', 'Tyuter'), ('oquv_bolimi', "O'quv Bo'limi"), ('dekanat', 'Dekanat'), ('kadirlar', "Kadirlar Bo'limi"), ('kutubxona', 'Kutubxona'), ('ombor', 'Ombor'), ('ai', 'AI'), ('inspektsiya', 'Inspektsiya (Nazorat)')], default='tyuter', max_length=20),
        ),
    ]
