# Generated by Django 6.0.2 on 2026-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('furniture', 'Jihoz'), ('electronics', 'Elektronika'), ('stationery', 'Kanselyariya'), ('other', 'Boshqa')], default='other', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='dona', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
