# Generated by Django 6.0.2 on 2026-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('inspection_comment', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('rector_approved', models.BooleanField(default=False)),
                ('rector_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='plans/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
