# Generated by Django 6.0.2 on 2026-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workplan',
            name='title',
        ),
        migrations.AddField(
            model_name='workplan',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='description_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workplan',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workplan',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workplan',
            name='title_uz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
