# Generated by Django 6.0.2 on 2026-02-14 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_workplan_description_remove_workplan_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanalysis',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonanalysis',
            name='group',
            field=models.CharField(default='101-A', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonanalysis',
            name='time',
            field=models.CharField(default='09:00', max_length=50),
        ),
    ]
