# Generated by Django 6.0.2 on 2026-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lessonanalysis_plan_file_lessonanalysis_result_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanalysis',
            name='hr_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='hr_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='rector_decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
