# Generated by Django 6.0.2 on 2026-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_lessonanalysis_hr_comment_lessonanalysis_hr_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonanalysis',
            old_name='hr_comment',
            new_name='dekanat_comment',
        ),
        migrations.RenameField(
            model_name='lessonanalysis',
            old_name='rector_approved',
            new_name='rector_signed',
        ),
        migrations.RenameField(
            model_name='lessonanalysis',
            old_name='inspection_date',
            new_name='rector_signed_at',
        ),
        migrations.RemoveField(
            model_name='lessonanalysis',
            name='hr_status',
        ),
        migrations.RemoveField(
            model_name='lessonanalysis',
            name='inspection_comment',
        ),
        migrations.RemoveField(
            model_name='lessonanalysis',
            name='rector_decision',
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='dekanat_document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='edu_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lessonanalysis',
            name='grade',
            field=models.CharField(blank=True, choices=[('alo', "A'lo"), ('yaxshi', 'Yaxshi'), ('qoniqarli', 'Qoniqarli'), ('hayfsan', 'Hayfsan'), ('shtraf', 'Shtraf'), ('haydash', 'Haydash')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lessonanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — AI analyzed, awaiting grading'), ('graded', "Graded — O'quv Bo'limi graded"), ('sent_to_dekanat', 'Sent to Dekanat'), ('dekanat_ready', 'Dekanat Ready — document prepared for Rektor'), ('rector_signed', 'Rector Signed — executed'), ('archived', 'Archived — no action needed')], default='pending', max_length=20),
        ),
    ]
