# Generated by Django 6.0.2 on 2026-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_rename_hr_comment_lessonanalysis_dekanat_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanalysis',
            name='inspection_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — AI analyzed, awaiting grading'), ('graded', "Graded — O'quv Bo'limi graded (Internal)"), ('sent_to_inspection', 'Sent to Inspection - Awaiting approval'), ('returned_to_edu', 'Returned to Edu Dept - Inspection rejected'), ('sent_to_dekanat', 'Sent to Dekanat - Inspection approved (Punishment)'), ('dekanat_ready', 'Dekanat Ready — document prepared for Rektor'), ('ready_for_rector', 'Ready for Rector - Inspection approved (No Punishment)'), ('rector_signed', 'Rector Signed — executed'), ('archived', 'Archived — no action needed')], default='pending', max_length=20),
        ),
    ]
