from rest_framework import viewsets, permissions, status
from .permissions import IsAdminOrRektor
from rest_framework.decorators import action
from rest_framework.response import Response
from django.utils import timezone
from .models import User
from education.models import LessonAnalysis, WorkPlan
from library.models import Book
from inventory.models import Item
from performance.models import KPIRecord
from .serializers import (
    UserSerializer, LessonAnalysisSerializer,
    WorkPlanSerializer, BookSerializer, ItemSerializer, KPIRecordSerializer
)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_permissions(self):
        if self.action == 'me':
            return [permissions.IsAuthenticated()]
        return [permissions.IsAuthenticated(), IsAdminOrRektor()]

    def perform_create(self, serializer):
        user = serializer.save()
        if 'password' in self.request.data:
            user.set_password(self.request.data['password'])
            user.save()

    def perform_update(self, serializer):
        user = serializer.save()
        if 'password' in self.request.data and self.request.data['password']:
            user.set_password(self.request.data['password'])
            user.save()

    @action(detail=False, methods=['get'])
    def me(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)


from education.services import AIService


class LessonAnalysisViewSet(viewsets.ModelViewSet):
    queryset = LessonAnalysis.objects.all().order_by('-created_at')
    serializer_class = LessonAnalysisSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        # AI auto-assigns a preliminary grade
        score = serializer.validated_data.get('score', 0)
        grade = LessonAnalysis.calculate_grade(score)
        serializer.save(grade=grade, status='pending')

    @action(detail=False, methods=['post'])
    def analyze(self, request):
        """AI analyzes lesson - creates a new analysis with pending status."""
        topic = request.data.get('topic', "Noma'lum mavzu")
        teacher_name = request.data.get('teacher', "Noma'lum o'qituvchi")

        plan_file = request.FILES.get('plan')
        video_file = request.FILES.get('video')

        result = AIService.analyze_lesson(topic, teacher_name)

        from django.core.files.base import ContentFile
        result_content = f"""
        AI ANALYSIS RESULT
        ------------------
        Teacher: {teacher_name}
        Topic: {topic}
        Score: {result['score']}%
        Grade: {result['grade']}
        
        Summary:
        {result['summary']}
        
        Suggestion:
        {result['suggestion']}
        
        Generated by Smart Univ AI
        """
        result_file = ContentFile(
            result_content.encode('utf-8'),
            name=f"analysis_{teacher_name}_{result['score']}.txt"
        )

        analysis = LessonAnalysis.objects.create(
            user=request.user,
            teacher=teacher_name,
            subject=topic,
            score=result['score'],
            grade=result['grade'],
            summary=result['summary'],
            suggestion=result['suggestion'],
            status='pending',
            plan_file=plan_file,
            video_file=video_file,
            result_file=result_file
        )

        serializer = self.get_serializer(analysis)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    @action(detail=True, methods=['post'])
    def grade(self, request, pk=None):
        """O'quv Bo'limi grades the analysis and optionally forwards to Dekanat."""
        analysis = self.get_object()

        grade = request.data.get('grade', analysis.grade)
        edu_comment = request.data.get('edu_comment', '')
        fine_amount = request.data.get('fine_amount')

        analysis.grade = grade
        analysis.edu_comment = edu_comment

        if grade == 'shtraf' and fine_amount:
            analysis.fine_amount = fine_amount

        # If grade needs action (hayfsan, shtraf, haydash) -> send to dekanat
        if LessonAnalysis.needs_action(grade):
            analysis.status = 'sent_to_dekanat'
        else:
            analysis.status = 'archived'  # Good grades are archived

        analysis.save()
        serializer = self.get_serializer(analysis)
        return Response(serializer.data)

    @action(detail=True, methods=['post'])
    def prepare_document(self, request, pk=None):
        """Dekanat prepares official document and sends to Rektor."""
        analysis = self.get_object()

        dekanat_document = request.data.get('dekanat_document', '')
        dekanat_comment = request.data.get('dekanat_comment', '')

        analysis.dekanat_document = dekanat_document
        analysis.dekanat_comment = dekanat_comment
        analysis.status = 'dekanat_ready'
        analysis.save()

        serializer = self.get_serializer(analysis)
        return Response(serializer.data)

    @action(detail=True, methods=['post'])
    def rector_sign(self, request, pk=None):
        """Rektor signs the document and puts it into execution."""
        analysis = self.get_object()

        rector_comment = request.data.get('rector_comment', '')

        analysis.rector_signed = True
        analysis.rector_comment = rector_comment
        analysis.rector_signed_at = timezone.now()
        analysis.status = 'rector_signed'
        analysis.save()

        serializer = self.get_serializer(analysis)
        return Response(serializer.data)


class WorkPlanViewSet(viewsets.ModelViewSet):
    queryset = WorkPlan.objects.all().order_by('-created_at')
    serializer_class = WorkPlanSerializer
    permission_classes = [permissions.IsAuthenticated]


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('-created_at')
    serializer_class = BookSerializer
    permission_classes = [permissions.IsAuthenticated]


class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all().order_by('category')
    serializer_class = ItemSerializer
    permission_classes = [permissions.IsAuthenticated]


class KPIRecordViewSet(viewsets.ModelViewSet):
    queryset = KPIRecord.objects.all().order_by('-month')
    serializer_class = KPIRecordSerializer
    permission_classes = [permissions.IsAuthenticated]


class DashboardStatsView(viewsets.ViewSet):
    permission_classes = [permissions.IsAuthenticated]

    def list(self, request):
        total_analyses = LessonAnalysis.objects.count()
        pending_count = LessonAnalysis.objects.filter(status='pending').count()
        problem_count = LessonAnalysis.objects.filter(grade__in=['hayfsan', 'shtraf', 'haydash']).count()

        avg_score = 0
        if total_analyses:
            from django.db.models import Avg
            avg_score = LessonAnalysis.objects.aggregate(avg=Avg('score'))['avg'] or 0

        stats = [
            {'label': 'Jami talabalar', 'value': '4,520', 'icon': 'Users', 'color': 'text-blue-600', 'bg': 'bg-blue-100'},
            {'label': "O'rtacha o'zlashtirish", 'value': f'{avg_score:.0f}%', 'icon': 'Activity', 'color': 'text-green-600', 'bg': 'bg-green-100'},
            {'label': 'Jami tahlillar', 'value': str(total_analyses), 'icon': 'FileText', 'color': 'text-purple-600', 'bg': 'bg-purple-100'},
            {'label': 'Muammoli darslar', 'value': str(problem_count), 'icon': 'BarChart', 'color': 'text-orange-600', 'bg': 'bg-orange-100'},
        ]
        return Response(stats)
