from rest_framework import viewsets, permissions, status
from .permissions import IsAdminOrRektor
from rest_framework.decorators import action
from rest_framework.response import Response
from .models import User
from education.models import LessonAnalysis, WorkPlan
from library.models import Book
from inventory.models import Item
from performance.models import KPIRecord
from .serializers import (
    UserSerializer, LessonAnalysisSerializer,
    WorkPlanSerializer, BookSerializer, ItemSerializer, KPIRecordSerializer
)

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_permissions(self):
        if self.action == 'me':
            return [permissions.IsAuthenticated()]
        return [permissions.IsAuthenticated(), IsAdminOrRektor()]

    def perform_create(self, serializer):
        user = serializer.save()
        if 'password' in self.request.data:
            user.set_password(self.request.data['password'])
            user.save()

    def perform_update(self, serializer):
        user = serializer.save()
        if 'password' in self.request.data and self.request.data['password']:
            user.set_password(self.request.data['password'])
            user.save()

    @action(detail=False, methods=['get'])
    def me(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)

from education.services import AIService

class LessonAnalysisViewSet(viewsets.ModelViewSet):
    queryset = LessonAnalysis.objects.all().order_by('-created_at')
    serializer_class = LessonAnalysisSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        if serializer.validated_data.get('score', 100) < 20:
            serializer.save(status='flagged')
        else:
            serializer.save(status='approved')

    @action(detail=False, methods=['post'])
    def analyze(self, request):
        topic = request.data.get('topic', 'Noma\'lum mavzu')
        teacher_name = request.data.get('teacher', 'Noma\'lum o\'qituvchi')
        
        # Files
        plan_file = request.FILES.get('plan')
        video_file = request.FILES.get('video')
        
        # Simulate AI processing
        result = AIService.analyze_lesson(topic, teacher_name)
        
        # Create a dummy result file
        from django.core.files.base import ContentFile
        result_content = f"""
        AI ANALYSIS RESULT
        ------------------
        Teacher: {teacher_name}
        Topic: {topic}
        Score: {result['score']}%
        
        Summary:
        {result['summary']}
        
        Suggestion:
        {result['suggestion']}
        
        Generated by Smart Univ AI
        """
        result_file = ContentFile(result_content.encode('utf-8'), name=f"analysis_{teacher_name}_{result['score']}.txt")
        
        # Create record
        analysis = LessonAnalysis.objects.create(
            user=request.user, 
            teacher=teacher_name,
            subject=topic, 
            score=result['score'],
            summary=result['summary'],
            suggestion=result['suggestion'],
            status=result['status'],
            plan_file=plan_file,
            video_file=video_file,
            result_file=result_file
        )
        
        serializer = self.get_serializer(analysis)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

class WorkPlanViewSet(viewsets.ModelViewSet):
    queryset = WorkPlan.objects.all().order_by('-created_at')
    serializer_class = WorkPlanSerializer
    permission_classes = [permissions.IsAuthenticated]

class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('-created_at')
    serializer_class = BookSerializer
    permission_classes = [permissions.IsAuthenticated]

class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all().order_by('category')
    serializer_class = ItemSerializer
    permission_classes = [permissions.IsAuthenticated]

class KPIRecordViewSet(viewsets.ModelViewSet):
    queryset = KPIRecord.objects.all().order_by('-month')
    serializer_class = KPIRecordSerializer
    permission_classes = [permissions.IsAuthenticated]

class DashboardStatsView(viewsets.ViewSet):
    permission_classes = [permissions.IsAuthenticated]

    def list(self, request):
        stats = [
            { 'label': 'Jami talabalar', 'value': '4,520', 'icon': 'Users', 'color': 'text-blue-600', 'bg': 'bg-blue-100' },
            { 'label': "O'rtacha o'zlashtirish", 'value': '78%', 'icon': 'Activity', 'color': 'text-green-600', 'bg': 'bg-green-100' },
            { 'label': 'Yangi hisobotlar', 'value': str(LessonAnalysis.objects.count()), 'icon': 'FileText', 'color': 'text-purple-600', 'bg': 'bg-purple-100' },
            { 'label': 'KPI ko\'rsatkichi', 'value': '92.5', 'icon': 'BarChart', 'color': 'text-orange-600', 'bg': 'bg-orange-100' },
        ]
        return Response(stats)
